### ISSUE TITLE
BOM missing z-screw?

### ISSUE THREAD

**Issue by andrewcaustralia** [revarbat/snappy-reprap#1]
Just noticed it wasn't listed; it appears you're using a separate z-screw however am I right to assume a fixed screw stepper would also be suitable? IE - http://imgur.com/2MpQk3C

**Comment by revarbat** [comment]
The lifter rods are only really needed for the v0.95 version of the printer.  I recommend a large thread size, though, so the z_sled parts man interface with them cleaner.

**Comment by andrewcaustralia** [comment]
Ah I get it now; was looking at the original pictures and trying to understand how they worked :-) :+1:
