### ISSUE TITLE
Amazon Links lead to unavailable items or confusing items

### ISSUE THREAD

**Issue by blade2005** [revarbat/snappy-reprap#11]
On BOM in the wiki, 
1. RAMPS kit is out of stock
2. Power supply, the link doesn't have a 120W or 300W option.
3. Cooling fan is out of stock, https://www.amazon.com/dp/B00E1JO8SG should replace it
4. Speaker wire is unavailable. i couldn't find something suitable 22GA thats as cheap.
5. The heated bed is also unavailable, though I found https://www.amazon.com/dp/B00QQ5Q3BI/ which might be substituted.

**Comment by revarbat** [comment]
If this in reference to the v1.1 or the v1.5 Wiki BOM?

**Comment by blade2005** [comment]
I just saw this response. Sorry about the delay. I got to this from reprap.org
http://reprap.org/wiki/Snappy which at the bottom led me to this 
https://github.com/revarbat/snappy-reprap/wiki/BOM

**Comment by revarbat** [comment]
Okay, that's the v1.1 links then.

**Comment by blade2005** [comment]
It looks like all the links have been updated. Thanks :D
