### ISSUE TITLE
J head compatibility 

### ISSUE THREAD

**Issue by AliAmjid** [revarbat/snappy-reprap#18]
Hi, I just want to ask if I can use [this](http://www.geeetech.com/wiki/index.php/PEEK_J-head_short-distance) or [ this](http://www.geeetech.com/wiki/index.php/PEEK_J-head_long-distance) j head instead of that one in BoM.

**Comment by revarbat** [comment]
The first one yes, the second one no.  The second one is designed for use with a bowden tube as opposed to a direct drive like the snappy has.

**Comment by keithellis74** [comment]
Hi, this looks like a great project.  Will this work printed in PLA?
