### ISSUE TITLE
non manifold duplacate edge (error resulting from addition of zrot(90))

### ISSUE THREAD

**Issue by ejans** [revarbat/snappy-reprap#20]
I can't normalize the STLs starting with bridge_segment_parts. (plain make after make cleaner)
If i revert to commit 80a1b47 the problem is fixed.

Diff from 80a1b47 to 29f7a1 for bridge_segment_parts shows only the addition of zrot(90)

I'm running plain Debian 9.0
Openscad version 2015.03-2

Kind regards,

Evert

**Comment by revarbat** [comment]
Fixed in 217f8d4
