### ISSUE TITLE
[Question] Minimim build volume to print all the files ?

### ISSUE THREAD

**Issue by Shotman** [revarbat/snappy-reprap#21]
I didn't see it on the wiki but what's the minimum build volume required to print all the part ? I guess it's self replicating but for instance I have a Monoprice MP Select Mini with a 120*120*120 build volume and I was wondering if it's big enough ?

Thanks

**Comment by revarbat** [comment]
I’m afraid the parts, by default, need a 150mm cube build volume for Snappy 3.0. 

You *can* change the part lengths in config.scad and regenerate the models for a smaller build volume, but I fear some parts like the extruder platform can’t get much smaller than they already are.
