### ISSUE TITLE
Where/How to install jhead_lock_parts and jhead_barrel_fan_shroud

### ISSUE THREAD

**Issue by bjbeare** [revarbat/snappy-reprap#25]
I've completed the build using v3.1... about to power it up. I don't see how to mount the fans, the jhead_lock_parts or the jhead_barrel_fan_shroud.

**Comment by ManuGithubSteam** [comment]
The 3.1 does not have a part cooling fan, it is missing. Thats why 3.1 is not officially released. I think it is the last part that is missing.

I myself opted for the 3.1 with the e3v6 hotend as they are easy to come by. The e3dv6lite clone has a cooling fan, so i dont see the need for the cooling fan (for the v6). I belive i have read that the jhead does not require active cooling anyway.

However im working on a part to make the part cooling assembly from 3.0 useable in 3.1.  for the parts printed with the v5lite clone i have.

Here is the part but it is untested.

[Fan Holder_Snappy_v1.zip](https://github.com/revarbat/snappy-reprap/files/2691412/Fan.Holder_Snappy_v1.zip)

**Comment by revarbat** [comment]
I'm afraid for the longest time I had the equivalent of writer's block when designing that part.  I finally got past that and I have a workable print cooling fan in my repo, though I'm still finishing the J-Head barrel cooling fan.

**Comment by bjbeare** [comment]
I've done a redesign of the xy carriage. I'm pretty happy with the result. I'll post on thingiverse after I test the latest version (sometime this week).
