### ISSUE TITLE
BOM error? Rail Z Endcap

### ISSUE THREAD

**Issue by karlexceed** [revarbat/snappy-reprap#27]
Snappy 3 BOM states: "1 | Rail Z Endcap"

But the assembly guide Top Brace Assembly ([https://github.com/revarbat/snappy-reprap/wiki/v3.0-Assembly#top-brace-assembly](here)) Step 2 indicates needing two. Also, the wording is inconsistent (rail Z endcap vs Z rail endstop).

**Comment by ManuGithubSteam** [comment]
You need two. There seems to be an error..

**Comment by revarbat** [comment]
Thanks!  I've fixed the entry.
