### ISSUE TITLE
mk42 bed config

### ISSUE THREAD

**Issue by boelle** [revarbat/snappy-reprap#30]
have anyone made a config for the mk42 bed? it uses the same 4 corner holes but have 2 extra at the center

and then its 250x210 instead

**Comment by ManuGithubSteam** [comment]
Im just starting out with my snappy and printing parts but i would suggest its just a mater of changes in the config of the fw how wide the bed is. i belive you dont need the two holes in the middle. There is nothing to attach to anyway.

**Comment by boelle** [comment]
the bed is more wide than mk42 but just uses the same corner holes, so there needs to be ~50 more space for the bed

and yes the 2 center holes are needed, the prevent the bed from warping when it gets hot
