### ISSUE TITLE
BUG: rail_z_endcap_parts.stl still has Endstop holders

### ISSUE THREAD

**Issue by ManuGithubSteam** [revarbat/snappy-reprap#35]
Hi 

Quite a simple miss i guess:

in the 3.1 Design the Endstops where moved down to the Z Base parts. 
However, in the rail_z_endcap_parts.stl there are still present.

These collide with the z lifter rods.

![image](https://user-images.githubusercontent.com/3456994/51807557-66f8f880-2288-11e9-807a-dc0f1bc1c343.png)

I fixed it in TinkerCAD but dont know that much of scad to do it there.

Just to raise awareness :-)

**Comment by revarbat** [comment]
Fixed in 6f06297
