### ISSUE TITLE
Can not get makefile to exicute

### ISSUE THREAD

**Issue by mlpage34** [revarbat/snappy-reprap#43]
I have installed lmde3 and installed openscad, after changing the makefile, I try to run make, and get a syntax error on the first line <!DOCTYPE html>. 
I have tried my google fu and it is not strong. can someone point me in a direction to go in order to find a solution?

**Comment by revarbat** [comment]
What error does it give?

**Comment by mlpage34** [comment]
Makefile:7: *** missing separator.  Stop.

**Comment by ManuGithubSteam** [comment]
What system do you use ? Linux or Windows or Mac ? The text editor you use must be capable of using the right end of line (Unix) and you need to save it in unix format.

**Comment by mlpage34** [comment]
that was using linux. I can install a different distribution, thats not a problem. I have ubuntu, xubuntu, lmde, kali, debian 9, kubuntu, and lubuntu. also, I can use a diffrent editor. I used nano to modify it last time. It was my intention to use LMDE 3 only for 3d printing, but if I would have better support with fedora, debian, or ubuntu, I would swich

**Comment by ManuGithubSteam** [comment]
No thats all fine. So its a logical error in the file, Made by you and no machine can exacly say what it is but its on line 7.
best idea: See the orginal file and compare line 7. It seems some seperator is missing. It seems like you should not modiy that line (7). I did not when i made mine.

I attached mine. It works.

[Makefile.txt](https://github.com/revarbat/snappy-reprap/files/2949713/Makefile.txt)

**Comment by ManuGithubSteam** [comment]
could you solve it ?

**Comment by mlpage34** [comment]
Yes, it was because I didnt clone the repository. the makefile was full of html and xml language. once I cloned, everything was good
