### ISSUE TITLE
In addition to Issue #3

### ISSUE THREAD

**Issue by Salandora** [revarbat/snappy-reprap#5]
In addition to Issue #3 you also need to wrap the lines
https://github.com/revarbat/snappy-reprap/blob/master/rail_segment_parts.scad#L84-L90

**Comment by ArktekniK** [comment]
Was just about to report this too

**Comment by revarbat** [comment]
[v1.1 fb36d72] Fixed issue #5: wiring access holes not needed with crossbeam wall styles.
 3 files changed, 23 insertions(+), 8 deletions(-)
