### ISSUE TITLE
YZ Joiner cable hole problem with corrugated style walls

### ISSUE THREAD

**Issue by ArktekniK** [revarbat/snappy-reprap#6]
Hi there, just thought I'd mention that I noticed when this object is sliced without support, the printer will attempt to print unsupported overhangs. This is because the bridge is not a direct line across the gap.

![corrugated wall wiring hole](https://cloud.githubusercontent.com/assets/9900921/10525985/dc57397c-737f-11e5-99ab-30d63597cf8f.png)

**Comment by revarbat** [comment]
Oh dear.  I  never really print with the corrugated walls, so I didn't see this.  There will be a number of places with this issue, I think.  It should be fixable by making a frame around the wiring access holes, though.

**Comment by revarbat** [comment]
[master 0e05308] Fixed issue #6: Wiring access holes need frames on corrugated walls.
 4 files changed, 42 insertions(+)
