### ISSUE TITLE
J-head compatible

### ISSUE THREAD

**Issue by farfadet46** [revarbat/snappy-reprap#8]
Hi, i found your project very intersting but i only this model of Jhead (http://www.threedeeprints.com/product/3d-cam-metal-j-head-v6-hot-end-for-reprap-3d-printer-1-75mm-filament-direct-feed-extruder-0-4mm-nozzle/)
So, can you explain me how to put it in the extruder bridge ?
i have already printed it but it don't stay in.
https://github.com/revarbat/snappy-reprap/blob/master/docs/assembly/extruder_bridge_assembly_4_after.png

regards,

**Comment by popotropopic3** [comment]
I used a dremel. I would be happy to chat.

**Comment by farfadet46** [comment]
A dremel oO, no no no, the j-head are too small to fit and stay in.
i think 'maybe' i need this part ?
https://sc01.alicdn.com/kf/HTB1rm4_GXXXXXb2XVXXq6xXFXXXO/200663255/HTB1rm4_GXXXXXb2XVXXq6xXFXXXO.jpg

Sorry for my english, i'm French, so, some time i don't use the correct grammar :p

**Comment by popotropopic3** [comment]
My French is far worse than your English.  haha. Are you using a bowden
setup?

**Comment by farfadet46** [comment]
hi ! no i think bowden isn't interesting for your printer

i think the thick of the platform is smaller than the J-head

https://sc01.alicdn.com/kf/HTB1rm4_GXXXXXb2XVXXq6xXFXXXO/200663255/HTB1rm4_GXXXXXb2XVXXq6xXFXXXO.jpg
on this picture you can see 4.6 mm my J-head is about 5.9mm

the platform is about 4.5mm.
so maybe you can tell me what i can do to fix the j6head to the platform ?
i see on this https://github.com/revarbat/snappy-reprap/blob/master/docs/assembly/extruder_bridge_assembly_8_after.png maybe the component for fixing the ventilator can fix the j-head in place too ?

I just printed the platform for now ; about 6 hours it's my biggest time of print.
and 2 legs haha :)

best regards

**Comment by popotropopic3** [comment]
I just used a few layers of Kapton tape. That helped make it a tight fit.

**Comment by farfadet46** [comment]
i need 1mm of kapton tape XD ok i print the "extruder_fan_shroud_parts.stl"
wait and see ;)
big thanks !

so, i tested the "fan shoud" so it isn't fixing my probem :/ maybe i need another j-head ?
or maybe you can made an adaptator  ? :p

**Comment by farfadet46** [comment]
Hello, i just made an adaptator i'm surprised about how it's easy to make :)
![capture](https://cloud.githubusercontent.com/assets/11613522/24326292/aa4f48ea-11ab-11e7-879d-0fc1788805d4.PNG)

if you want to add to your files (i named it 13... i don't know why XD)
[13.zip](https://github.com/revarbat/snappy-reprap/files/870382/13.zip)

**Comment by revarbat** [comment]
The E3Dv6 head does not conform to the J-head standard. It conforms to the E3D mount standard.  :) It has different mount dimensions.

I worry that the all-metal E3Dv6 isn't workable anyways. I suspect it will carry too much heat up to its mount point and warp the PLA there. As it is, a J-head with its PEEK barrel gets hot enough to warp the PLA mount point if you don't have the cooling fan running on it. Let me know how your adaptor works for you.

**Comment by farfadet46** [comment]
Hi, you'r right, it's a big mistake about the cooling sytem and the feeding system too XD

i need to make a new support for the extruder's motor too ; so i stop making stupid stuff for now :p
Anyway you make a very good work on this !

best regards
Fabien

**Comment by popotropopic3** [comment]
I figured that out the hard way...
